project_id = "wvyhtvaiacdghjkysmfw"

[functions.analyze-sentiment]
verify_jwt = false

[functions.scrape-google-news]
verify_jwt = false

[functions.scrape-tradingview]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false
